package Interfaz.Administrador;

public class AdministradorRegistro extends javax.swing.JFrame {

    public AdministradorRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static void mostrarRegistroAdmin() {
        AdministradorRegistro administradorR = new AdministradorRegistro();
        administradorR.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        nombres_apellidos_campo = new javax.swing.JTextField();
        telefono_campo = new javax.swing.JTextField();
        cedula_campo = new javax.swing.JTextField();
        correo_ = new javax.swing.JTextField();
        usuario_campo = new javax.swing.JTextField();
        register_admin_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        nombres_apellidos_campo.setForeground(new java.awt.Color(255, 255, 255));
        nombres_apellidos_campo.setBorder(null);
        nombres_apellidos_campo.setOpaque(false);
        background.add(nombres_apellidos_campo);
        nombres_apellidos_campo.setBounds(380, 80, 290, 30);

        telefono_campo.setForeground(new java.awt.Color(255, 255, 255));
        telefono_campo.setBorder(null);
        telefono_campo.setOpaque(false);
        background.add(telefono_campo);
        telefono_campo.setBounds(380, 130, 290, 30);

        cedula_campo.setForeground(new java.awt.Color(255, 255, 255));
        cedula_campo.setBorder(null);
        cedula_campo.setOpaque(false);
        background.add(cedula_campo);
        cedula_campo.setBounds(380, 190, 290, 30);

        correo_.setForeground(new java.awt.Color(255, 255, 255));
        correo_.setBorder(null);
        correo_.setOpaque(false);
        background.add(correo_);
        correo_.setBounds(380, 240, 290, 30);

        usuario_campo.setForeground(new java.awt.Color(255, 255, 255));
        usuario_campo.setBorder(null);
        usuario_campo.setOpaque(false);
        background.add(usuario_campo);
        usuario_campo.setBounds(380, 290, 290, 30);

        register_admin_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/RegistroAdmin Screen.png"))); // NOI18N
        background.add(register_admin_screen);
        register_admin_screen.setBounds(0, 0, 700, 547);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField cedula_campo;
    private javax.swing.JTextField correo_;
    private javax.swing.JTextField nombres_apellidos_campo;
    private javax.swing.JLabel register_admin_screen;
    private javax.swing.JTextField telefono_campo;
    private javax.swing.JTextField usuario_campo;
    // End of variables declaration//GEN-END:variables
}
