package Interfaz.Administrador;

public class Administrador extends javax.swing.JFrame {

    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public static void mostrarAdmin() {
        Administrador administrador = new Administrador();
        administrador.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        asignar_eliminar_registros_pacientes = new javax.swing.JButton();
        boton_asignar_cita = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        administrador_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        asignar_eliminar_registros_pacientes.setBorderPainted(false);
        asignar_eliminar_registros_pacientes.setContentAreaFilled(false);
        background.add(asignar_eliminar_registros_pacientes);
        asignar_eliminar_registros_pacientes.setBounds(230, 310, 230, 130);

        boton_asignar_cita.setBackground(new java.awt.Color(255, 255, 255));
        boton_asignar_cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Asignardefault.png"))); // NOI18N
        boton_asignar_cita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        boton_asignar_cita.setBorderPainted(false);
        boton_asignar_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_asignar_citaActionPerformed(evt);
            }
        });
        background.add(boton_asignar_cita);
        boton_asignar_cita.setBounds(100, 140, 250, 140);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1);
        jButton1.setBounds(370, 140, 250, 140);

        administrador_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Administración Screen.png"))); // NOI18N
        background.add(administrador_screen);
        administrador_screen.setBounds(0, -30, 970, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_asignar_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_asignar_citaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_asignar_citaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrador_screen;
    private javax.swing.JButton asignar_eliminar_registros_pacientes;
    private javax.swing.JPanel background;
    private javax.swing.JButton boton_asignar_cita;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
