package Interfaz.Administrador;

import static Interfaz.Administrador.Administrador.mostrarAdmin;
import static Interfaz.Administrador.Pacientes.AdministradorEliminarRegistro.mostrarEliminarRegistro;
import static Interfaz.Administrador.Pacientes.AdministradorRegistro.mostrarRegistroAdmin;
import java.awt.Cursor;
import javax.swing.ImageIcon;

public class AdministradorPacientes extends javax.swing.JFrame {

    public AdministradorPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Administrador de Pacientes");
    }

    public static void mostrarAdminPacientes() {
        AdministradorPacientes adminP = new AdministradorPacientes();
        adminP.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_agregar_paciente = new javax.swing.JButton();
        boton_eliminar_paciente = new javax.swing.JButton();
        back_boton = new javax.swing.JButton();
        administrador_pacientes_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        boton_agregar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/AgPacienteDef.png"))); // NOI18N
        boton_agregar_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_agregar_pacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_agregar_pacienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_agregar_pacienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_agregar_pacienteMouseReleased(evt);
            }
        });
        boton_agregar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(boton_agregar_paciente);
        boton_agregar_paciente.setBounds(110, 200, 310, 170);

        boton_eliminar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/ElPacienteDef.png"))); // NOI18N
        boton_eliminar_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_eliminar_pacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_eliminar_pacienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_eliminar_pacienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_eliminar_pacienteMouseReleased(evt);
            }
        });
        boton_eliminar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminar_pacienteActionPerformed(evt);
            }
        });
        jPanel1.add(boton_eliminar_paciente);
        boton_eliminar_paciente.setBounds(540, 200, 310, 170);

        back_boton.setBorderPainted(false);
        back_boton.setContentAreaFilled(false);
        back_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                back_botonMouseMoved(evt);
            }
        });
        back_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_botonMouseExited(evt);
            }
        });
        back_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_botonActionPerformed(evt);
            }
        });
        jPanel1.add(back_boton);
        back_boton.setBounds(-10, 563, 50, 40);

        administrador_pacientes_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/Registros pacientes.png"))); // NOI18N
        jPanel1.add(administrador_pacientes_screen);
        administrador_pacientes_screen.setBounds(0, 0, 960, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_agregar_pacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_pacienteMouseEntered

    }//GEN-LAST:event_boton_agregar_pacienteMouseEntered

    private void boton_agregar_pacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_pacienteMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/AgPacienteDef.png"));
        boton_agregar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_agregar_pacienteMouseExited

    private void boton_agregar_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_pacienteMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/AgPacientePressed.png"));
        boton_agregar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_agregar_pacienteMousePressed

    private void boton_agregar_pacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_pacienteMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/AgPacienteOver.png"));
        boton_agregar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_agregar_pacienteMouseReleased

    private void boton_eliminar_pacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_pacienteMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/ElPacienteOver.png"));
        boton_eliminar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_pacienteMouseEntered

    private void boton_eliminar_pacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_pacienteMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/ElPacienteDef.png"));
        boton_eliminar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_pacienteMouseExited

    private void boton_eliminar_pacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_pacienteMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/ElPacienteOver.png"));
        boton_eliminar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_pacienteMouseReleased

    private void boton_eliminar_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_pacienteMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/ElPacientePressed.png"));
        boton_eliminar_paciente.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_pacienteMousePressed

    private void boton_eliminar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminar_pacienteActionPerformed
        dispose();
        mostrarEliminarRegistro();
    }//GEN-LAST:event_boton_eliminar_pacienteActionPerformed

    private void boton_agregar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_pacienteActionPerformed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorPaciente/AgPacienteOver.png"));
        boton_agregar_paciente.setIcon(II);
        dispose();
        mostrarRegistroAdmin();
    }//GEN-LAST:event_boton_agregar_pacienteActionPerformed

    private void back_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_botonActionPerformed
        dispose();
        mostrarAdmin();
    }//GEN-LAST:event_back_botonActionPerformed

    private void back_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseMoved
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_back_botonMouseMoved

    private void back_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseExited
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_back_botonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrador_pacientes_screen;
    private javax.swing.JButton back_boton;
    private javax.swing.JButton boton_agregar_paciente;
    private javax.swing.JButton boton_eliminar_paciente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
