package Interfaz.Administrador;

import static Interfaz.Administrador.Administrador.mostrarAdmin;
import java.awt.Cursor;
import javax.swing.ImageIcon;

public class AdministradorMedicos extends javax.swing.JFrame {

    public AdministradorMedicos() {
        initComponents();
        this.setTitle("Administrador de Medicos");
        this.setLocationRelativeTo(null);
    }

    public static void mostrarAdminMedicos() { //MUESTRA LA VENTANA LOGIN
        AdministradorMedicos AdminMedicos = new AdministradorMedicos();
        AdminMedicos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_agregar_medico = new javax.swing.JButton();
        boton_eliminar_medico = new javax.swing.JButton();
        back_boton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1052, 606, 0, 0);

        boton_agregar_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/AgMedicosDef.png"))); // NOI18N
        boton_agregar_medico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_agregar_medicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_agregar_medicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_agregar_medicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_agregar_medicoMouseReleased(evt);
            }
        });
        boton_agregar_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_medicoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_agregar_medico);
        boton_agregar_medico.setBounds(110, 200, 310, 170);

        boton_eliminar_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/ElimMedicosDef.png"))); // NOI18N
        boton_eliminar_medico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_eliminar_medicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_eliminar_medicoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_eliminar_medicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boton_eliminar_medicoMouseReleased(evt);
            }
        });
        jPanel1.add(boton_eliminar_medico);
        boton_eliminar_medico.setBounds(540, 200, 310, 170);

        back_boton.setBorderPainted(false);
        back_boton.setContentAreaFilled(false);
        back_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                back_botonMouseMoved(evt);
            }
        });
        back_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_botonMouseExited(evt);
            }
        });
        back_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_botonActionPerformed(evt);
            }
        });
        jPanel1.add(back_boton);
        back_boton.setBounds(-10, 570, 50, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/Registros médicos.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_agregar_medicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_medicoMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/AgMedicosaOver.png"));
        boton_agregar_medico.setIcon(II);
    }//GEN-LAST:event_boton_agregar_medicoMouseEntered

    private void boton_agregar_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_agregar_medicoActionPerformed

    private void boton_agregar_medicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_medicoMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/AgMedicosPressed.png"));
        boton_agregar_medico.setIcon(II);

    }//GEN-LAST:event_boton_agregar_medicoMousePressed

    private void boton_agregar_medicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_medicoMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/AgMedicosDef.png"));
        boton_agregar_medico.setIcon(II);
    }//GEN-LAST:event_boton_agregar_medicoMouseExited

    private void boton_agregar_medicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_agregar_medicoMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/AgMedicosDef.png"));
        boton_agregar_medico.setIcon(II);
    }//GEN-LAST:event_boton_agregar_medicoMouseReleased

    private void boton_eliminar_medicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_medicoMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/ElimMedicosaOver.png"));
        boton_eliminar_medico.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_medicoMouseEntered

    private void boton_eliminar_medicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_medicoMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/ElimMedicosDef.png"));
        boton_eliminar_medico.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_medicoMouseExited

    private void boton_eliminar_medicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_medicoMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/ElimMedicosPressed.png"));
        boton_eliminar_medico.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_medicoMousePressed

    private void boton_eliminar_medicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_eliminar_medicoMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministradorMedico/ElimMedicosaOver.png"));
        boton_eliminar_medico.setIcon(II);
    }//GEN-LAST:event_boton_eliminar_medicoMouseReleased

    private void back_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_botonActionPerformed
        dispose();
        mostrarAdmin();
    }//GEN-LAST:event_back_botonActionPerformed

    private void back_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseMoved
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_back_botonMouseMoved

    private void back_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseExited
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_back_botonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_boton;
    private javax.swing.JButton boton_agregar_medico;
    private javax.swing.JButton boton_eliminar_medico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
