package Interfaz.Administrador;

import static Interfaz.Administrador.AdministradorPacientes.mostrarAdminPacientes;
import java.awt.Cursor;

public class Administrador extends javax.swing.JFrame {

    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Administrador");

    }

    public static void mostrarAdmin() {
        Administrador administrador = new Administrador();
        administrador.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        asignar_eliminar_registros_pacientes = new javax.swing.JButton();
        administrador_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        asignar_eliminar_registros_pacientes.setBorderPainted(false);
        asignar_eliminar_registros_pacientes.setContentAreaFilled(false);
        asignar_eliminar_registros_pacientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                asignar_eliminar_registros_pacientesMouseMoved(evt);
            }
        });
        asignar_eliminar_registros_pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asignar_eliminar_registros_pacientesMouseExited(evt);
            }
        });
        asignar_eliminar_registros_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_eliminar_registros_pacientesActionPerformed(evt);
            }
        });
        background.add(asignar_eliminar_registros_pacientes);
        asignar_eliminar_registros_pacientes.setBounds(230, 310, 230, 130);

        administrador_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Administración Screen.png"))); // NOI18N
        background.add(administrador_screen);
        administrador_screen.setBounds(0, -30, 970, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignar_eliminar_registros_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_eliminar_registros_pacientesActionPerformed
        dispose();
        mostrarAdminPacientes();
    }//GEN-LAST:event_asignar_eliminar_registros_pacientesActionPerformed

    private void asignar_eliminar_registros_pacientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignar_eliminar_registros_pacientesMouseMoved
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));    }//GEN-LAST:event_asignar_eliminar_registros_pacientesMouseMoved

    private void asignar_eliminar_registros_pacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignar_eliminar_registros_pacientesMouseExited
        this.setCursor(DEFAULT_CURSOR);    }//GEN-LAST:event_asignar_eliminar_registros_pacientesMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrador_screen;
    private javax.swing.JButton asignar_eliminar_registros_pacientes;
    private javax.swing.JPanel background;
    // End of variables declaration//GEN-END:variables
}
