/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Administrador;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrea
 */
public class EliminarCita extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCita
     */
    public EliminarCita() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultar_boton = new javax.swing.JButton();
        agregar_boton = new javax.swing.JButton();
        eliminarcita_boton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(960, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 600));
        jPanel1.setLayout(null);

        consultar_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/condef.png"))); // NOI18N
        consultar_boton.setBorderPainted(false);
        consultar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultar_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                consultar_botonMouseReleased(evt);
            }
        });
        jPanel1.add(consultar_boton);
        consultar_boton.setBounds(590, 340, 100, 40);

        agregar_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agdef.png"))); // NOI18N
        agregar_boton.setBorderPainted(false);
        agregar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregar_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregar_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregar_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                agregar_botonMouseReleased(evt);
            }
        });
        jPanel1.add(agregar_boton);
        agregar_boton.setBounds(80, 300, 140, 40);

        eliminarcita_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elidef.png"))); // NOI18N
        eliminarcita_boton.setBorderPainted(false);
        eliminarcita_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseReleased(evt);
            }
        });
        eliminarcita_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcita_botonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarcita_boton);
        eliminarcita_boton.setBounds(590, 500, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/eliminar cita Administrador.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/conover.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseEntered

    private void consultar_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/condef.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseExited

    private void consultar_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/conpressed.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMousePressed

    private void consultar_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/conover.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseReleased

    private void agregar_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agover.png"));
        agregar_boton.setIcon(II);
    }//GEN-LAST:event_agregar_botonMouseEntered

    private void agregar_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agdef.png"));
        agregar_boton.setIcon(II);
    }//GEN-LAST:event_agregar_botonMouseExited

    private void agregar_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agpressed.png"));
        agregar_boton.setIcon(II);
    }//GEN-LAST:event_agregar_botonMousePressed

    private void agregar_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agover.png"));
        agregar_boton.setIcon(II);
    }//GEN-LAST:event_agregar_botonMouseReleased

    private void eliminarcita_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/eliover.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseEntered

    private void eliminarcita_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elidef.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseExited

    private void eliminarcita_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elipressed.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMousePressed

    private void eliminarcita_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/eliover.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseReleased

    private void eliminarcita_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcita_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarcita_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCita().setVisible(true);
            }
        });
       
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_boton;
    private javax.swing.JButton consultar_boton;
    private javax.swing.JButton eliminarcita_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
