package Interfaz.Administrador.Pacientes;

import static Interfaz.Administrador.Administrador.mostrarAdmin;
import static Interfaz.Administrador.AdministradorPacientes.mostrarAdminPacientes;
import java.awt.Cursor;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static Logica.Pacientes.ArchivoPacientes.eliminarPacientes;

public class EliminarPaciente extends javax.swing.JFrame {

    public EliminarPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Eliminar Pacientes");
    }

    public static void mostrarEliminarRegistro() {
        EliminarPaciente eliminarRegistro = new EliminarPaciente();
        eliminarRegistro.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        cedula_campo = new javax.swing.JTextField();
        usuario_campo = new javax.swing.JTextField();
        contraseña_campo = new javax.swing.JTextField();
        eliminar_boton = new javax.swing.JButton();
        back_boton = new javax.swing.JButton();
        administrador_eliminar_registro_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 547));

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        cedula_campo.setForeground(new java.awt.Color(255, 255, 255));
        cedula_campo.setBorder(null);
        cedula_campo.setOpaque(false);
        background.add(cedula_campo);
        cedula_campo.setBounds(390, 160, 280, 40);

        usuario_campo.setForeground(new java.awt.Color(255, 255, 255));
        usuario_campo.setBorder(null);
        usuario_campo.setOpaque(false);
        background.add(usuario_campo);
        usuario_campo.setBounds(390, 230, 280, 30);

        contraseña_campo.setForeground(new java.awt.Color(255, 255, 255));
        contraseña_campo.setBorder(null);
        contraseña_campo.setOpaque(false);
        background.add(contraseña_campo);
        contraseña_campo.setBounds(390, 292, 280, 30);

        eliminar_boton.setForeground(new java.awt.Color(204, 204, 204));
        eliminar_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminardeAdmin/elimdef.png"))); // NOI18N
        eliminar_boton.setBorderPainted(false);
        eliminar_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                eliminar_botonMouseMoved(evt);
            }
        });
        eliminar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminar_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminar_botonMouseReleased(evt);
            }
        });
        eliminar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_botonActionPerformed(evt);
            }
        });
        background.add(eliminar_boton);
        eliminar_boton.setBounds(410, 360, 230, 40);

        back_boton.setBorderPainted(false);
        back_boton.setContentAreaFilled(false);
        back_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                back_botonMouseMoved(evt);
            }
        });
        back_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_botonMouseExited(evt);
            }
        });
        back_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_botonActionPerformed(evt);
            }
        });
        background.add(back_boton);
        back_boton.setBounds(0, 500, 40, 40);

        administrador_eliminar_registro_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminarUsuario.png"))); // NOI18N
        background.add(administrador_eliminar_registro_screen);
        administrador_eliminar_registro_screen.setBounds(0, -10, 710, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_botonActionPerformed
        String cedula = cedula_campo.getText();
        String usuario = usuario_campo.getText();
        String contraseña = contraseña_campo.getText();
        try {
            int resultado = eliminarPacientes(cedula, usuario, contraseña);

            if (resultado == 0) {
                JOptionPane.showMessageDialog(this, "El usuario ha sido eliminado exitosamente.", "Usuario Eliminado", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                mostrarAdmin();
            } else if (resultado == 1) {
                JOptionPane.showMessageDialog(this, "No se encontró un usuario que coincida con los datos proporcionados.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (resultado == 2) {
                JOptionPane.showMessageDialog(this, "Hubo un problema al escribir en el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al acceder al archivo de usuarios.", "Error de archivo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_eliminar_botonActionPerformed

    private void eliminar_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMouseMoved
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_eliminar_botonMouseMoved

    private void eliminar_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminardeAdmin/elimdef.png"));
        eliminar_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_eliminar_botonMouseExited

    private void back_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_botonActionPerformed
        dispose();
        mostrarAdminPacientes();
    }//GEN-LAST:event_back_botonActionPerformed

    private void back_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseExited
       this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_back_botonMouseExited

    private void back_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_botonMouseMoved
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_back_botonMouseMoved

    private void eliminar_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminardeAdmin/elimover.png"));
        eliminar_boton.setIcon(II);
    }//GEN-LAST:event_eliminar_botonMouseEntered

    private void eliminar_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminardeAdmin/elimpressed.png"));
        eliminar_boton.setIcon(II);
    }//GEN-LAST:event_eliminar_botonMousePressed

    private void eliminar_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EliminardeAdmin/elimover.png"));
        eliminar_boton.setIcon(II);
    }//GEN-LAST:event_eliminar_botonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrador_eliminar_registro_screen;
    private javax.swing.JButton back_boton;
    private javax.swing.JPanel background;
    private javax.swing.JTextField cedula_campo;
    private javax.swing.JTextField contraseña_campo;
    private javax.swing.JButton eliminar_boton;
    private javax.swing.JTextField usuario_campo;
    // End of variables declaration//GEN-END:variables
}
