package Interfaz.Administrador.Citas;

import static Logica.Medicos.ArchivoMedicos.cargarMedicosDesdeArchivo;
import Logica.Medicos.Medico;
import java.io.IOException;
import java.util.List;

public class ConsultarTodosMedicos extends javax.swing.JFrame {

    public ConsultarTodosMedicos() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarTodosLosMedicos();
    }

    public static void mostrarConsultarTodosMedicos() throws IOException { //MUESTRA LA VENTANA LOGIN
        ConsultarTodosMedicos consultarTodosMedicos = new ConsultarTodosMedicos();
        consultarTodosMedicos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lista_medicos_text = new javax.swing.JScrollPane();
        lista_medicos_text_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Medicos");
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        lista_medicos_text_area.setColumns(20);
        lista_medicos_text_area.setRows(5);
        lista_medicos_text.setViewportView(lista_medicos_text_area);

        background.add(lista_medicos_text);
        lista_medicos_text.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodosLosMedicos() throws IOException {
        List<Medico> medicos = cargarMedicosDesdeArchivo("listamedicos.txt");
        // Limpiar el JTextArea antes de añadir nuevo contenido
        lista_medicos_text_area.setText("");
        // Añadir cabecera
        lista_medicos_text_area.append(String.format("%-15s %-30s %s\n", "CÉDULA", "MEDICO", "ESPECIALIDAD"));

        for (int i = 0; i < medicos.size(); i++) {
            Medico medico = medicos.get(i);
            // Utilizar getCedula() para obtener la cédula del médico en vez del índice
            lista_medicos_text_area.append(String.format("%-15s %-30s %s\n", medico.getCedula(), medico.getNombres_apellidos(), medico.getEspecialidad()));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JScrollPane lista_medicos_text;
    private javax.swing.JTextArea lista_medicos_text_area;
    // End of variables declaration//GEN-END:variables
}
