/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Administrador.Citas;

import javax.swing.ImageIcon;

/**
 *
 * @author Andrea
 */
public class EliminarCita extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCita
     */
    public EliminarCita() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        agregarcedula_boton = new javax.swing.JButton();
        eliminarcita_boton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        volver_boton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(780, 605));
        setMinimumSize(new java.awt.Dimension(780, 605));
        setPreferredSize(new java.awt.Dimension(780, 605));

        jPanel1.setMaximumSize(new java.awt.Dimension(779, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(779, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(779, 630));
        jPanel1.setLayout(null);

        jComboBox2.setBackground(new java.awt.Color(197, 220, 244));
        jComboBox2.setEditable(true);
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(360, 360, 270, 40);

        agregarcedula_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agdef.png"))); // NOI18N
        agregarcedula_boton.setBorderPainted(false);
        agregarcedula_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarcedula_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarcedula_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarcedula_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                agregarcedula_botonMouseReleased(evt);
            }
        });
        jPanel1.add(agregarcedula_boton);
        agregarcedula_boton.setBounds(110, 280, 120, 40);

        eliminarcita_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elidef.png"))); // NOI18N
        eliminarcita_boton.setBorderPainted(false);
        eliminarcita_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminarcita_botonMouseReleased(evt);
            }
        });
        jPanel1.add(eliminarcita_boton);
        eliminarcita_boton.setBounds(500, 470, 110, 40);

        jComboBox1.setBackground(new java.awt.Color(197, 220, 244));
        jComboBox1.setEditable(true);
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(360, 230, 270, 40);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 220, 210, 30);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 380, 230, 40);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 450, 230, 40);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 520, 230, 30);

        volver_boton.setBorderPainted(false);
        volver_boton.setContentAreaFilled(false);
        jPanel1.add(volver_boton);
        volver_boton.setBounds(0, 560, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionEliminarCita/elimcita (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 779, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void agregarcedula_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarcedula_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agover.png"));
        agregarcedula_boton.setIcon(II);
    }//GEN-LAST:event_agregarcedula_botonMouseEntered

    private void agregarcedula_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarcedula_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agdef.png"));
        agregarcedula_boton.setIcon(II);
    }//GEN-LAST:event_agregarcedula_botonMouseExited

    private void agregarcedula_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarcedula_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agpressed.png"));
        agregarcedula_boton.setIcon(II);
    }//GEN-LAST:event_agregarcedula_botonMousePressed

    private void agregarcedula_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarcedula_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/agover.png"));
        agregarcedula_boton.setIcon(II);
    }//GEN-LAST:event_agregarcedula_botonMouseReleased

    private void eliminarcita_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/eliover.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseEntered

    private void eliminarcita_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elidef.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseExited

    private void eliminarcita_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/elipressed.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMousePressed

    private void eliminarcita_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarcita_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/BotonesAG_ELCitas/eliover.png"));
        eliminarcita_boton.setIcon(II);
    }//GEN-LAST:event_eliminarcita_botonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarcedula_boton;
    private javax.swing.JButton eliminarcita_boton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volver_boton;
    // End of variables declaration//GEN-END:variables
}
