package Interfaz;

import Logica.Medicos.ArchivoMedicos;
import Logica.Medicos.Medico;
import java.io.IOException;
import java.util.List;

public class Citas extends javax.swing.JFrame {

    public Citas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void actualizarComboBoxMedicos() {
        try {
            // Carga la lista de médicos desde el archivo.
            List<Medico> medicos = ArchivoMedicos.cargarMedicosDesdeArchivo("listamedicos.txt");

            // Guarda temporalmente el elemento en el índice 0 si existe.
            String itemEnIndiceCero = medicos_jcombox.getItemCount() > 0 ? medicos_jcombox.getItemAt(0) : null;

            // Limpia el JComboBox, manteniendo solo el primer elemento si este existe.
            medicos_jcombox.removeAllItems();
            if (itemEnIndiceCero != null) {
                medicos_jcombox.addItem(itemEnIndiceCero); // Re-añade el primer elemento guardado.
            }

            // Añade los nuevos elementos de la lista de médicos, comenzando desde el índice 1.
            for (Medico medico : medicos) {
                // Evita duplicar el primer elemento si ya fue añadido.
                if (!medico.getNombres_apellidos().equals(itemEnIndiceCero)) {
                    medicos_jcombox.addItem(medico.getNombres_apellidos()); // Asume que Medico tiene un método getNombres_apellidos().
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Manejo de errores, por ejemplo, mostrando un mensaje al usuario.
        }
    }

    public static void mostrarCitas() { //MUESTRA LA VENTANA LOGIN
        Citas citas = new Citas();
        citas.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        especialidades_jcombobox = new javax.swing.JComboBox<>();
        medicos_jcombox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendar Cita");
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setLayout(null);

        especialidades_jcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione especialidad", "Optometria Ortoptica", "Cataratas", "Glaucoma", "Oftalmologia General", "Oftalmologia Pediatrica", "Retina y Vitreo" }));
        especialidades_jcombobox.setToolTipText("");
        especialidades_jcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidades_jcomboboxActionPerformed(evt);
            }
        });
        background.add(especialidades_jcombobox);
        especialidades_jcombobox.setBounds(370, 100, 159, 22);

        medicos_jcombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Medico" }));
        medicos_jcombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicos_jcomboxActionPerformed(evt);
            }
        });
        background.add(medicos_jcombox);
        medicos_jcombox.setBounds(380, 160, 210, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void especialidades_jcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidades_jcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidades_jcomboboxActionPerformed

    private void medicos_jcomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicos_jcomboxActionPerformed
        actualizarComboBoxMedicos();
    }//GEN-LAST:event_medicos_jcomboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> especialidades_jcombobox;
    public javax.swing.JComboBox<String> medicos_jcombox;
    // End of variables declaration//GEN-END:variables
}
