package Interfaz;

import java.awt.Cursor;

public class Especialidades extends javax.swing.JFrame {

    public Especialidades() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        optometria_boton = new javax.swing.JButton();
        cataratas_boton = new javax.swing.JButton();
        glaucoma_boton = new javax.swing.JButton();
        oftalmologia_general_boton = new javax.swing.JButton();
        oftalmologia_pediatrica_boton = new javax.swing.JButton();
        retina_vitreo_boton = new javax.swing.JButton();
        especialidades_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Especialidades");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(965, 605));
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(960, 600));
        Background.setLayout(null);

        optometria_boton.setBorderPainted(false);
        optometria_boton.setContentAreaFilled(false);
        optometria_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                optometria_botonMouseMoved(evt);
            }
        });
        optometria_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optometria_botonMouseExited(evt);
            }
        });
        optometria_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optometria_botonActionPerformed(evt);
            }
        });
        Background.add(optometria_boton);
        optometria_boton.setBounds(30, 20, 250, 220);

        cataratas_boton.setBorderPainted(false);
        cataratas_boton.setContentAreaFilled(false);
        cataratas_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseMoved(evt);
            }
        });
        cataratas_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseExited(evt);
            }
        });
        Background.add(cataratas_boton);
        cataratas_boton.setBounds(360, 20, 250, 220);

        glaucoma_boton.setBorderPainted(false);
        glaucoma_boton.setContentAreaFilled(false);
        glaucoma_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseMoved(evt);
            }
        });
        glaucoma_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseExited(evt);
            }
        });
        Background.add(glaucoma_boton);
        glaucoma_boton.setBounds(700, 20, 240, 220);

        oftalmologia_general_boton.setBorderPainted(false);
        oftalmologia_general_boton.setContentAreaFilled(false);
        oftalmologia_general_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseMoved(evt);
            }
        });
        oftalmologia_general_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseExited(evt);
            }
        });
        Background.add(oftalmologia_general_boton);
        oftalmologia_general_boton.setBounds(0, 300, 290, 230);

        oftalmologia_pediatrica_boton.setBorderPainted(false);
        oftalmologia_pediatrica_boton.setContentAreaFilled(false);
        oftalmologia_pediatrica_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseMoved(evt);
            }
        });
        oftalmologia_pediatrica_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseExited(evt);
            }
        });
        Background.add(oftalmologia_pediatrica_boton);
        oftalmologia_pediatrica_boton.setBounds(340, 350, 310, 170);

        retina_vitreo_boton.setBorderPainted(false);
        retina_vitreo_boton.setContentAreaFilled(false);
        retina_vitreo_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseMoved(evt);
            }
        });
        retina_vitreo_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseExited(evt);
            }
        });
        Background.add(retina_vitreo_boton);
        retina_vitreo_boton.setBounds(700, 330, 230, 190);

        especialidades_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Especialidades Screen.png"))); // NOI18N
        Background.add(especialidades_screen);
        especialidades_screen.setBounds(-10, -30, 950, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optometria_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseMoved

        this.setCursor(new Cursor(Cursor.HAND_CURSOR)); //HACE QUE EL CURSOR SE CONVIERTA EN MANITO
    }//GEN-LAST:event_optometria_botonMouseMoved

    private void optometria_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseExited

        this.setCursor(DEFAULT_CURSOR); // HACE QUE EL CURSOR SE VUELVA DEFAULT
    }//GEN-LAST:event_optometria_botonMouseExited

    private void cataratas_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cataratas_botonMouseMoved

    private void cataratas_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseExited
        // TODO add your handling code here:
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_cataratas_botonMouseExited

    private void glaucoma_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_glaucoma_botonMouseMoved

    private void glaucoma_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseExited
        // TODO add your handling code here:
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_glaucoma_botonMouseExited

    private void oftalmologia_general_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_oftalmologia_general_botonMouseMoved

    private void oftalmologia_general_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseExited
        // TODO add your handling code here:
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_oftalmologia_general_botonMouseExited

    private void oftalmologia_pediatrica_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseMoved

    private void oftalmologia_pediatrica_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseExited
        // TODO add your handling code here:
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseExited

    private void retina_vitreo_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_retina_vitreo_botonMouseMoved

    private void retina_vitreo_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseExited
        // TODO add your handling code here:
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_retina_vitreo_botonMouseExited

    private void optometria_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optometria_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optometria_botonActionPerformed

    public static void mostrarEspecialidades() { //MUESTRA LA VENTANA ESPECIALIDADES
        Especialidades especialidades = new Especialidades();
        especialidades.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton cataratas_boton;
    private javax.swing.JLabel especialidades_screen;
    private javax.swing.JButton glaucoma_boton;
    private javax.swing.JButton oftalmologia_general_boton;
    private javax.swing.JButton oftalmologia_pediatrica_boton;
    private javax.swing.JButton optometria_boton;
    private javax.swing.JButton retina_vitreo_boton;
    // End of variables declaration//GEN-END:variables
}
