package Interfaz;

import static Interfaz.Instrucciones.mostrarInstrucciones;
import java.awt.Cursor;
import javax.swing.ImageIcon;

public class Especialidades extends javax.swing.JFrame {

    public Especialidades() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        optometria_boton = new javax.swing.JButton();
        cataratas_boton = new javax.swing.JButton();
        glaucoma_boton = new javax.swing.JButton();
        oftalmologia_general_boton = new javax.swing.JButton();
        oftalmologia_pediatrica_boton = new javax.swing.JButton();
        retina_vitreo_boton = new javax.swing.JButton();
        especialidades_screen = new javax.swing.JLabel();
        barra_menu = new javax.swing.JMenuBar();
        opciones_menu = new javax.swing.JMenu();
        instrucciones_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Especialidades");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(965, 635));
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(960, 600));
        Background.setLayout(null);

        optometria_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesOrtoptica/OptOdefault.png"))); // NOI18N
        optometria_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        optometria_boton.setContentAreaFilled(false);
        optometria_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                optometria_botonMouseMoved(evt);
            }
        });
        optometria_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optometria_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optometria_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                optometria_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                optometria_botonMouseReleased(evt);
            }
        });
        optometria_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optometria_botonActionPerformed(evt);
            }
        });
        Background.add(optometria_boton);
        optometria_boton.setBounds(130, 100, 200, 210);

        cataratas_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesCataratas/Cataratasdefault.png"))); // NOI18N
        cataratas_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        cataratas_boton.setContentAreaFilled(false);
        cataratas_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseMoved(evt);
            }
        });
        cataratas_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cataratas_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cataratas_botonMouseReleased(evt);
            }
        });
        cataratas_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cataratas_botonActionPerformed(evt);
            }
        });
        Background.add(cataratas_boton);
        cataratas_boton.setBounds(370, 100, 200, 210);

        glaucoma_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGlaucoma/Glaucomadefault.png"))); // NOI18N
        glaucoma_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        glaucoma_boton.setContentAreaFilled(false);
        glaucoma_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseMoved(evt);
            }
        });
        glaucoma_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                glaucoma_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                glaucoma_botonMouseReleased(evt);
            }
        });
        Background.add(glaucoma_boton);
        glaucoma_boton.setBounds(610, 100, 200, 210);

        oftalmologia_general_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGeneral/Generaldefault.png"))); // NOI18N
        oftalmologia_general_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        oftalmologia_general_boton.setContentAreaFilled(false);
        oftalmologia_general_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseMoved(evt);
            }
        });
        oftalmologia_general_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oftalmologia_general_botonMouseReleased(evt);
            }
        });
        Background.add(oftalmologia_general_boton);
        oftalmologia_general_boton.setBounds(130, 350, 200, 210);

        oftalmologia_pediatrica_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesPediatrica/Pediatricadefault.png"))); // NOI18N
        oftalmologia_pediatrica_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        oftalmologia_pediatrica_boton.setContentAreaFilled(false);
        oftalmologia_pediatrica_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseMoved(evt);
            }
        });
        oftalmologia_pediatrica_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oftalmologia_pediatrica_botonMouseReleased(evt);
            }
        });
        oftalmologia_pediatrica_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oftalmologia_pediatrica_botonActionPerformed(evt);
            }
        });
        Background.add(oftalmologia_pediatrica_boton);
        oftalmologia_pediatrica_boton.setBounds(370, 350, 200, 210);

        retina_vitreo_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesRetinaVitrio/RVdefault.png"))); // NOI18N
        retina_vitreo_boton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        retina_vitreo_boton.setContentAreaFilled(false);
        retina_vitreo_boton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseMoved(evt);
            }
        });
        retina_vitreo_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                retina_vitreo_botonMouseReleased(evt);
            }
        });
        Background.add(retina_vitreo_boton);
        retina_vitreo_boton.setBounds(610, 350, 200, 210);

        especialidades_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesFeed/FeedOjos.png"))); // NOI18N
        Background.add(especialidades_screen);
        especialidades_screen.setBounds(0, 0, 950, 600);

        opciones_menu.setText("Opciones");

        instrucciones_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Instrucciones/Instrucciones Icono.png"))); // NOI18N
        instrucciones_menu.setText("Instrucciones");
        instrucciones_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrucciones_menuActionPerformed(evt);
            }
        });
        opciones_menu.add(instrucciones_menu);

        barra_menu.add(opciones_menu);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optometria_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseMoved

        this.setCursor(new Cursor(Cursor.HAND_CURSOR)); //HACE QUE EL CURSOR SE CONVIERTA EN MANITO
    }//GEN-LAST:event_optometria_botonMouseMoved

    private void optometria_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesOrtoptica/OptOdefault.png"));
        optometria_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR); // HACE QUE EL CURSOR SE VUELVA DEFAULT
    }//GEN-LAST:event_optometria_botonMouseExited

    private void cataratas_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cataratas_botonMouseMoved

    private void cataratas_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesCataratas/Cataratasdefault.png"));
        cataratas_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_cataratas_botonMouseExited

    private void glaucoma_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_glaucoma_botonMouseMoved

    private void glaucoma_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGlaucoma/Glaucomadefault.png"));
        glaucoma_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_glaucoma_botonMouseExited

    private void oftalmologia_general_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_oftalmologia_general_botonMouseMoved

    private void oftalmologia_general_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGeneral/Generaldefault.png"));
        oftalmologia_general_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_oftalmologia_general_botonMouseExited

    private void oftalmologia_pediatrica_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseMoved

    private void oftalmologia_pediatrica_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesPediatrica/Pediatricadefault.png"));
        oftalmologia_pediatrica_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseExited

    private void retina_vitreo_botonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseMoved
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_retina_vitreo_botonMouseMoved

    private void retina_vitreo_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesRetinaVitrio/RVdefault.png"));
        retina_vitreo_boton.setIcon(II);
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_retina_vitreo_botonMouseExited

    private void optometria_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optometria_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optometria_botonActionPerformed

    private void instrucciones_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrucciones_menuActionPerformed
        mostrarInstrucciones();            //MUESTRA LA VENTANA INSTRUCCIONES
    }//GEN-LAST:event_instrucciones_menuActionPerformed

    private void optometria_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesOrtoptica/OptOover.png"));
        optometria_boton.setIcon(II);
    }//GEN-LAST:event_optometria_botonMouseEntered

    private void optometria_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesOrtoptica/OptOpressed.png"));
        optometria_boton.setIcon(II);
    }//GEN-LAST:event_optometria_botonMousePressed

    private void optometria_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optometria_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesOrtoptica/OptOover.png"));
        optometria_boton.setIcon(II);
    }//GEN-LAST:event_optometria_botonMouseReleased

    private void cataratas_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesCataratas/Cataratasover.png"));
        cataratas_boton.setIcon(II);
    }//GEN-LAST:event_cataratas_botonMouseEntered

    private void cataratas_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesCataratas/Catarataspressed.png"));
        cataratas_boton.setIcon(II);
    }//GEN-LAST:event_cataratas_botonMousePressed

    private void cataratas_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cataratas_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesCataratas/Cataratasover.png"));
        cataratas_boton.setIcon(II);
    }//GEN-LAST:event_cataratas_botonMouseReleased

    private void glaucoma_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGlaucoma/Glaucomaover.png"));
        glaucoma_boton.setIcon(II);
    }//GEN-LAST:event_glaucoma_botonMouseEntered

    private void glaucoma_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGlaucoma/Glaucomapressed.png"));
        glaucoma_boton.setIcon(II);
    }//GEN-LAST:event_glaucoma_botonMousePressed

    private void glaucoma_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glaucoma_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGlaucoma/Glaucomaover.png"));
        glaucoma_boton.setIcon(II);
    }//GEN-LAST:event_glaucoma_botonMouseReleased

    private void cataratas_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cataratas_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cataratas_botonActionPerformed

    private void oftalmologia_general_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGeneral/Generalover.png"));
        oftalmologia_general_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_general_botonMouseEntered

    private void oftalmologia_general_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGeneral/Generalover.png"));
        oftalmologia_general_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_general_botonMouseReleased

    private void oftalmologia_general_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_general_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesGeneral/Generalpressed.png"));
        oftalmologia_general_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_general_botonMousePressed

    private void oftalmologia_pediatrica_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oftalmologia_pediatrica_botonActionPerformed

    private void oftalmologia_pediatrica_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesPediatrica/Pediatricaover.png"));
        oftalmologia_pediatrica_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseEntered

    private void oftalmologia_pediatrica_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesPediatrica/Pediatricapressed.png"));
        oftalmologia_pediatrica_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMousePressed

    private void oftalmologia_pediatrica_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oftalmologia_pediatrica_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesPediatrica/Pediatricaover.png"));
        oftalmologia_pediatrica_boton.setIcon(II);
    }//GEN-LAST:event_oftalmologia_pediatrica_botonMouseReleased

    private void retina_vitreo_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesRetinaVitrio/RVover.png"));
        retina_vitreo_boton.setIcon(II);
    }//GEN-LAST:event_retina_vitreo_botonMouseEntered

    private void retina_vitreo_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesRetinaVitrio/RVpressed.png"));
        retina_vitreo_boton.setIcon(II);
    }//GEN-LAST:event_retina_vitreo_botonMousePressed

    private void retina_vitreo_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retina_vitreo_botonMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/Interfaz/Imagenes/EspecialidadesRetinaVitrio/RVover.png"));
        retina_vitreo_boton.setIcon(II);
    }//GEN-LAST:event_retina_vitreo_botonMouseReleased

    public static void mostrarEspecialidades() { //MUESTRA LA VENTANA ESPECIALIDADES
        Especialidades especialidades = new Especialidades();
        especialidades.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JButton cataratas_boton;
    private javax.swing.JLabel especialidades_screen;
    private javax.swing.JButton glaucoma_boton;
    private javax.swing.JMenuItem instrucciones_menu;
    private javax.swing.JButton oftalmologia_general_boton;
    private javax.swing.JButton oftalmologia_pediatrica_boton;
    private javax.swing.JMenu opciones_menu;
    private javax.swing.JButton optometria_boton;
    private javax.swing.JButton retina_vitreo_boton;
    // End of variables declaration//GEN-END:variables
}
