
package Interfaz;

import javax.swing.JFrame;

public class Instrucciones extends javax.swing.JFrame {

    
    public Instrucciones() {
        initComponents();
        // Establece el título de la ventana
        this.setTitle("Instrucciones");
        
        // Establece el tamaño de la ventana (ancho, alto)
        this.setSize(300, 200);
        
        this.setResizable(false);
        
        // Establece el comportamiento de cierre (terminar la aplicación cuando se cierra la ventana)
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Opcional: Configura la ubicación de la ventana en el centro de la pantalla
        this.setLocationRelativeTo(null);
         
    }

    public static void mostrarInstrucciones() {
        // Instancia la ventana
        Instrucciones instrucciones = new Instrucciones();
        
        // Hace visible la ventana
        instrucciones.setVisible(true);
    }

    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        titulo_instrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        titulo_instrucciones.setForeground(new java.awt.Color(0, 0, 0));
        titulo_instrucciones.setText("INSTRUCCIONES");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(titulo_instrucciones)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(titulo_instrucciones)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel titulo_instrucciones;
    // End of variables declaration//GEN-END:variables
}
