package Interfaz;

import javax.swing.JFrame;

public class Instrucciones extends javax.swing.JFrame {

    public Instrucciones() {
        //ATRIBUTOS
        initComponents();
        this.setTitle("Instrucciones");
        this.setResizable(false);
        // Establece el comportamiento de cierre (terminar la aplicación cuando se cierra la ventana)
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Opcional: Configura la ubicación de la ventana en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }

    public static void mostrarInstrucciones() {
        Instrucciones instrucciones = new Instrucciones(); //HACE QUE SE MUESTRE LA VENTANA INSTRUCCIONES
        instrucciones.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        instrucciones_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 447));
        getContentPane().setLayout(null);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(700, 447));

        instrucciones_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Instrucciones Screen.png"))); // NOI18N

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(instrucciones_screen)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(instrucciones_screen)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(Background);
        Background.setBounds(0, 0, 700, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel instrucciones_screen;
    // End of variables declaration//GEN-END:variables
}
