package Interfaz;

import static Interfaz.Instrucciones.mostrarInstrucciones;


public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
        this.setResizable(false);
    }

    public static void MostrarLogin(){
    Login login1 = new Login();
    login1.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        campo_usuario = new javax.swing.JTextField();
        campo_contraseña = new javax.swing.JTextField();
        login_screen = new javax.swing.JLabel();
        menu_barra = new javax.swing.JMenuBar();
        menu_opciones = new javax.swing.JMenu();
        menu_instrucciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(null);

        campo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        campo_usuario.setForeground(new java.awt.Color(0, 0, 0));
        campo_usuario.setBorder(null);
        background.add(campo_usuario);
        campo_usuario.setBounds(410, 170, 230, 30);

        campo_contraseña.setBackground(new java.awt.Color(255, 255, 255));
        campo_contraseña.setForeground(new java.awt.Color(0, 0, 0));
        campo_contraseña.setBorder(null);
        background.add(campo_contraseña);
        campo_contraseña.setBounds(410, 246, 230, 30);

        login_screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Login Screen.png"))); // NOI18N
        background.add(login_screen);
        login_screen.setBounds(0, -20, 730, 480);

        menu_opciones.setText("Opciones");

        menu_instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ICON2.png"))); // NOI18N
        menu_instrucciones.setText("Instrucciones");
        menu_instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_instruccionesActionPerformed(evt);
            }
        });
        menu_opciones.add(menu_instrucciones);

        menu_barra.add(menu_opciones);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_instruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_instruccionesActionPerformed
        mostrarInstrucciones();
    }//GEN-LAST:event_menu_instruccionesActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField campo_contraseña;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JLabel login_screen;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenuItem menu_instrucciones;
    private javax.swing.JMenu menu_opciones;
    // End of variables declaration//GEN-END:variables
}
