package Interfaz;

import Interfaz.P2;
import Interfaz.P3;
import Interfaz.P5;
import Interfaz.P6;
import Logica.Admin;
import javax.swing.JOptionPane;

public class P1 extends javax.swing.JFrame {
    
    public P1() {
        initComponents();
    }
    private static final P6 P6 = new P6();
    private static final P5 P5 = new P5();

    private static final P3 P3 = new P3();
    private static final P2 P2 = new P2();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_Titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistroUM = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRegistrarMedico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistroUM1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnRegistrarMedico1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistroUM2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        btnRegistrarMedico2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        JPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JMenu_Bar = new javax.swing.JMenuBar();
        JM_Opciones = new javax.swing.JMenu();
        JM_Instrucciones = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JM_Salir = new javax.swing.JMenuItem();
        JM_Modos = new javax.swing.JMenu();
        JRDBT_Claro = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        lbl_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setText("Horizon Wheels Versión beta 1.0");

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de Únidad Médica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel3)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegistroUM.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistroUM.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistroUM.setLabel("Registrar");
        btnRegistroUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUMActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Atras/Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrarMedico.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistrarMedico.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistrarMedico.setText("Registrar Médico");
        btnRegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMedicoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro de Únidad Médica");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel4)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegistroUM1.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistroUM1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistroUM1.setLabel("Registrar");
        btnRegistroUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUM1ActionPerformed(evt);
            }
        });

        btnCancelar1.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar1.setText("Atras/Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnRegistrarMedico1.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistrarMedico1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistrarMedico1.setText("Registrar Médico");
        btnRegistrarMedico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMedico1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro de Únidad Médica");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel5)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegistroUM2.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistroUM2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistroUM2.setLabel("Registrar");
        btnRegistroUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUM2ActionPerformed(evt);
            }
        });

        btnCancelar2.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCancelar2.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar2.setText("Atras/Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        btnRegistrarMedico2.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistrarMedico2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRegistrarMedico2.setText("Registrar Médico");
        btnRegistrarMedico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMedico2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IU/Logo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 70));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 90));

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblContraseña.setText("Contraseña");

        btnCrearCuenta.setBackground(new java.awt.Color(0, 51, 204));
        btnCrearCuenta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("CREAR CUENTA");
        btnCrearCuenta.setBorderPainted(false);
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(0, 51, 204));
        btnIniciar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.setBorderPainted(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Login.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtContraseña.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Log Screen.png"))); // NOI18N
        jLabel6.setText("Log Screen");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(255, 255, 255));
        JPanel.setForeground(new java.awt.Color(255, 255, 255));
        JPanel.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        JPanel.add(jTextField1);
        jTextField1.setBounds(410, 170, 230, 30);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(null);
        JPanel.add(jTextField2);
        jTextField2.setBounds(410, 242, 230, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Login Screen.png"))); // NOI18N
        jLabel7.setText("Login Screen");
        JPanel.add(jLabel7);
        jLabel7.setBounds(0, 0, 700, 447);

        JM_Opciones.setText("Opciones");
        JM_Opciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        JM_Instrucciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JM_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IU/ICON2.png"))); // NOI18N
        JM_Instrucciones.setText("Instrucciones");
        JM_Instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_InstruccionesActionPerformed(evt);
            }
        });
        JM_Opciones.add(JM_Instrucciones);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IU/ICON3.png"))); // NOI18N
        jMenuItem1.setText("Acerca De");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JM_Opciones.add(jMenuItem1);
        JM_Opciones.add(jSeparator1);

        JM_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JM_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IU/ICON1.png"))); // NOI18N
        JM_Salir.setText("Salir");
        JM_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_SalirActionPerformed(evt);
            }
        });
        JM_Opciones.add(JM_Salir);

        JMenu_Bar.add(JM_Opciones);

        JM_Modos.setText("Modos");
        JM_Modos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        JRDBT_Claro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonGroup1.add(JRDBT_Claro);
        JRDBT_Claro.setSelected(true);
        JRDBT_Claro.setText("Por Defecto");
        JM_Modos.add(JRDBT_Claro);

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("Rojo");
        JM_Modos.add(jRadioButtonMenuItem1);

        JMenu_Bar.add(JM_Modos);

        setJMenuBar(JMenu_Bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        P2.setVisible(true);
        P2.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String contraseña = txtContraseña.getText();
        int pos = Admin.verificar(usuario, contraseña);
        if (pos == -1) {
            JOptionPane.showMessageDialog(this, "DATOS INCORRECTOS");
        } else {
            
            JOptionPane.showMessageDialog(this, "HA INICIADO SESION");
            if (JRDBT_Claro.isSelected()) {
                P3.setVisible(true);
                P3.setLocationRelativeTo(null);
            } else {
                
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void JM_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JM_SalirActionPerformed

    private void JM_InstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_InstruccionesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JM_InstruccionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        P6.setVisible(true);
        P6.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnRegistroUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUMActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegistroUMActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMedicoActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_btnRegistrarMedicoActionPerformed

    private void btnRegistroUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUM1ActionPerformed
        // TODO add your handling code here:
        /*Datos*/
        
        //vistaRegistroPaciente vrp = new vistaRegistroPaciente(true,auxModal,auxIdPac);
        //vrp.show();
    }//GEN-LAST:event_btnRegistroUM1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnRegistrarMedico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMedico1ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnRegistrarMedico1ActionPerformed

    private void btnRegistroUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUM2ActionPerformed
        // TODO add your handling code here:
        /*Datos*/
        
        //vistaRegistroPaciente vrp = new vistaRegistroPaciente(true,auxModal,auxIdPac);
        //vrp.show();
    }//GEN-LAST:event_btnRegistroUM2ActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnRegistrarMedico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMedico2ActionPerformed
        
        

    }//GEN-LAST:event_btnRegistrarMedico2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JM_Instrucciones;
    private javax.swing.JMenu JM_Modos;
    private javax.swing.JMenu JM_Opciones;
    private javax.swing.JMenuItem JM_Salir;
    private javax.swing.JMenuBar JMenu_Bar;
    private javax.swing.JPanel JPanel;
    private javax.swing.JRadioButtonMenuItem JRDBT_Claro;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnCancelar1;
    public static javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIniciar;
    public static javax.swing.JButton btnRegistrarMedico;
    public static javax.swing.JButton btnRegistrarMedico1;
    public static javax.swing.JButton btnRegistrarMedico2;
    public static javax.swing.JButton btnRegistroUM;
    public static javax.swing.JButton btnRegistroUM1;
    public static javax.swing.JButton btnRegistroUM2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
