/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Administrador.Medicos;

import static Interfaz.Administrador.Administrador.mostrarAdmin;
import Interfaz.Administrador.Citas.EliminarCita;
import static Interfaz.Administrador.Citas.EliminarCita.ReiniciarCitasAgendas;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea
 */
public class ReiniciarArchivoMedico extends javax.swing.JFrame {

    /**
     * Creates new form ReiniciarArchivoMedico
     */
    public ReiniciarArchivoMedico() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    public static void mostrarReiniciarArchivoMedico() { //MUESTRA LA VENTANA LOGIN
        ReiniciarArchivoMedico reiniciar = new ReiniciarArchivoMedico();
        reiniciar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultar_boton = new javax.swing.JButton();
        volver_boton = new javax.swing.JButton();
        reiniciar_archivos_boton = new javax.swing.JButton();
        cedula_medico_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(675, 499));

        jPanel1.setPreferredSize(new java.awt.Dimension(675, 505));
        jPanel1.setLayout(null);

        consultar_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/ccdef.png"))); // NOI18N
        consultar_boton.setBorderPainted(false);
        consultar_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultar_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultar_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultar_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                consultar_botonMouseReleased(evt);
            }
        });
        consultar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_botonActionPerformed(evt);
            }
        });
        jPanel1.add(consultar_boton);
        consultar_boton.setBounds(270, 220, 130, 40);

        volver_boton.setBorderPainted(false);
        volver_boton.setContentAreaFilled(false);
        volver_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_botonActionPerformed(evt);
            }
        });
        jPanel1.add(volver_boton);
        volver_boton.setBounds(0, 440, 30, 30);

        reiniciar_archivos_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/radef.png"))); // NOI18N
        reiniciar_archivos_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reiniciar_archivos_botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reiniciar_archivos_botonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reiniciar_archivos_botonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reiniciar_archivos_botonMouseReleased(evt);
            }
        });
        jPanel1.add(reiniciar_archivos_boton);
        reiniciar_archivos_boton.setBounds(240, 300, 200, 40);

        cedula_medico_field.setBackground(new java.awt.Color(230, 227, 227));
        cedula_medico_field.setForeground(new java.awt.Color(0, 0, 0));
        cedula_medico_field.setBorder(null);
        cedula_medico_field.setOpaque(false);
        cedula_medico_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_medico_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(cedula_medico_field);
        cedula_medico_field.setBounds(240, 160, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/Reiniciar archivos (4).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -30, 675, 499);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_botonActionPerformed
        String id = cedula_medico_field.getText();
        try {
            if (id != null&& !id.isEmpty()) {
                EliminarCita.ReiniciarCitasAgendas(id);
            } else {
                JOptionPane.showMessageDialog(null, "Por favor escriba un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_consultar_botonActionPerformed

    private void cedula_medico_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_medico_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedula_medico_fieldActionPerformed

    private void volver_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_botonActionPerformed
        dispose();
        mostrarAdmin();
    }//GEN-LAST:event_volver_botonActionPerformed

    private void consultar_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/ccover.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseEntered

    private void consultar_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/ccdef.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseExited

    private void consultar_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/ccpressed.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMousePressed

    private void consultar_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/ccover.png"));
        consultar_boton.setIcon(II);
    }//GEN-LAST:event_consultar_botonMouseReleased

    private void reiniciar_archivos_botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciar_archivos_botonMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/raover.png"));
        reiniciar_archivos_boton.setIcon(II);
    }//GEN-LAST:event_reiniciar_archivos_botonMouseEntered

    private void reiniciar_archivos_botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciar_archivos_botonMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/radef.png"));
        reiniciar_archivos_boton.setIcon(II);
    }//GEN-LAST:event_reiniciar_archivos_botonMouseExited

    private void reiniciar_archivos_botonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciar_archivos_botonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/rapressed.png"));
        reiniciar_archivos_boton.setIcon(II);
    }//GEN-LAST:event_reiniciar_archivos_botonMousePressed

    private void reiniciar_archivos_botonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciar_archivos_botonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Interfaz/Imagenes/AdministracionReiniciarMedicos/raover.png"));
        reiniciar_archivos_boton.setIcon(II);
    }//GEN-LAST:event_reiniciar_archivos_botonMouseReleased

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula_medico_field;
    private javax.swing.JButton consultar_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reiniciar_archivos_boton;
    private javax.swing.JButton volver_boton;
    // End of variables declaration//GEN-END:variables
}
